FROM gcr.io/google_containers/kubectl:v1.0.7
MAINTAINER Liang <liang@maichong.it>
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && apt-get clean && rm -rf /var/lib/apt/lists/* 